---
- name: Set proper permissions to files.
  file:
    path: "{{ codebase_dir }}/sites/default/files"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 'ug+rwx'
    recurse: yes
    state: directory
  become: yes
  become_user: root
