---
- name: Make sure logs dir exists
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Touch and set proper permissions to drupal.log
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs/drupal.log"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0664
    state: touch
  become: yes
  become_user: root

- name: Make sure /etc/rsyslog.d dir exists
  file:
    path: /etc/rsyslog.d/
    state: directory
  become: yes
  become_user: root

- name: Install rsyslog config for Drupal syslog module
  template:
    src: rsyslog/drupal.conf
    dest: /etc/rsyslog.d/drupal.conf
  notify: Restart rsyslog
  become: yes
  become_user: root

- name: Enable syslog drupal module
  command: drush @{{ app_name }}.cur en syslog -y

- name: Make sure /etc/logrotate.d dir exists
  file:
    path: /etc/logrotate.d
    state: directory
  become: yes
  become_user: root

- name: setup logrotate.d script for drupal log rotation
  template:
    src: logrotate.d/drupal.j2
    dest: /etc/logrotate.d/drupal
  become: yes
  become_user: root
