---
- name: Remove .bak symlink and its contents, if it exists
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html.bak"
    follow: yes
    state: absent
  become: yes
  become_user: root

- name: Rename current symlink to .bak, if it exists
  command: "mv {{ deploy_webroot }}/{{ app_name }}/public_html {{ deploy_webroot }}/{{ app_name }}/public_html.bak"
  become: yes
  become_user: root

- name: Set new symlink to new live codebase
  file:
    dest: "{{ deploy_webroot }}/{{ app_name }}/public_html"
    src: "{{ deploy_webroot }}/{{ app_name }}/public_html.{{ deploy_build_id }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    state: link
  become: yes
  become_user: root

- name: Remove current build symlink
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html.build"
    state: absent
    follow: no
  become: yes
  become_user: root

- name: Check user/public_html symlink already exists
  stat: 
    path: "/home/{{ app_user }}/public_html"
  register: stat_public_symlink

- name: Create user/public_html symlink
  file:
    src: "{{ deploy_webroot }}/{{ app_name }}/public_html"
    dest: "/home/{{ app_user }}/public_html"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root
  when: stat_public_symlink.stat is not defined or not stat_public_symlink.stat.exists
