---
- name: Make sure logs dir exists
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Touch and set proper permissions to drupal.log
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs/drupal.log"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0664
    state: touch
  become: yes
  become_user: root

- include: "vars/{{ deploy_syslog_variant }}.yml"

- name: "Make sure {{ deploy_syslog_variant_confdir }} dir exists"
  file:
    path: "{{ deploy_syslog_variant_confdir }}"
    state: directory
  become: yes
  become_user: root

- name: "Install {{ deploy_syslog_variant }} config for Drupal syslog module"
  template:
    src: "{{ deploy_syslog_variant }}/drupal.conf.j2"
    dest: "{{ deploy_syslog_variant_confdir }}"
  notify: "Restart {{ deploy_syslog_variant }}"
  become: yes
  become_user: root

- name: Enable syslog drupal module
  command: drush @{{ app_name }}.cur en syslog -y

- name: Make sure /etc/logrotate.d dir exists
  file:
    path: /etc/logrotate.d
    state: directory
  become: yes
  become_user: root

- name: setup logrotate.d script for drupal log rotation
  template:
    src: logrotate.d/drupal.j2
    dest: /etc/logrotate.d/drupal
  become: yes
  become_user: root
