---
- name: create hotfix branch
  shell: "git checkout -b prod-{{ build }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: create build tag
  shell: "git tag {{ build }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: push hotfix branch
  shell: "git push origin prod-{{ build }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: push build tag
  shell: "git push origin {{ build }}"
  args:
    chdir: "{{ codebase_dir }}"
