---
- name: create hotfix branch
  shell: "git checkout -b prod-{{ deploy_build_id }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: create build tag
  shell: "git tag {{ deploy_build_id }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: push hotfix branch
  shell: "git push origin prod-{{ deploy_build_id }}"
  args:
    chdir: "{{ codebase_dir }}"

- name: push build tag
  shell: "git push origin {{ deploy_build_id }}"
  args:
    chdir: "{{ codebase_dir }}"
