---
- name: Make sure working directory exists
  file:
    path: "{{ working_dir }}"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes

- name: Require Twig via composer
  composer:
    command: "require"
    arguments: "twig/twig:~1.0"
    working_dir: "{{ working_dir }}"

- name: PHPize Twig C extension
  command: phpize
  args:
    chdir: "{{ working_dir }}/vendor/twig/twig/ext/twig"
    creates: "/home/vagrant/{{ app_name }}/vendor/twig/twig/ext/twig/configure"

- name: Configure Twig C extension
  command: "./configure" 
  args:
    chdir: "{{ working_dir }}/vendor/twig/twig/ext/twig"
    creates: "/home/vagrant/{{ app_name }}/vendor/twig/twig/ext/twig/Makefile"

- name: Make the Twig C extension
  command: make
  args:
    chdir: "{{ working_dir }}/vendor/twig/twig/ext/twig"
    creates: "/home/vagrant/{{ app_name }}/vendor/twig/twig/ext/twig/modules/twig.so"

- name: Register PHP's extension dir
  shell: php -i | grep extension_dir | cut -c 18-39
  register: php_extension_dir
  changed_when: False

- name: Install the Twig C extension
  command: make install
  args:
    chdir: "{{ working_dir }}/vendor/twig/twig/ext/twig"
    creates: "{{ php_extension_dir.stdout }}/twig.so"
  become: yes

- name: Create twig.ini
  template:
    src: 'php5/twig.ini.j2'
    dest: '/etc/php5/mods-available/twig.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes

- name: Configure twig.ini for FPM
  file:
    src: "/etc/php5/mods-available/twig.ini"
    dest: "/etc/php5/fpm/conf.d/20-twig.ini"
    state: link
  notify: 'Restart php5-fpm'
  become: yes
