---
- name: Cache clear all (D7)
  command: drush @{{ app_name }}.cur cc all
  ignore_errors: yes
  when: drupal_version == '7'

- name: Cache rebuild
  command: drush @{{ app_name }}.cur cache-rebuild
  ignore_errors: yes
  when: drupal_version == '8'
