---
- name: Sync current database to build database.
  command: drush sql-sync @{{ app_name }}.cur @{{ app_name }}.bld --create-db -y
  when: "deploy_target == 'prod'"
  
- name: Sync source database to build database.
  command: drush sql-sync @{{ app_name }}.src @{{ app_name }}.bld --create-db -y
  when: "deploy_target != 'prod' and app_drush_source is defined"
