---
- name: Check if drush_language is present
  stat:
    path: "{{ codebase_dir}}/sites/all/drush_language"
  register: drush_language_check

- name: Download drush_language module
  command: drush @{{ app_name }}.bld dl drush_language -y
  when: not drush_language_check.stat.exists

- name: Clear drush cache
  command: drush cc drush
  register: drush_cc_drush_result
  failed_when: "drush_cc_drush_result.rc != 0"

- name: Add all app languages
  command: drush @{{ app_name }}.bld language-add {{ item }}
  with_items: "{{ app_languages }}"
  ignore_errors: yes

- name: Enable all app languages
  command: drush @{{ app_name }}.bld language-enable {{ item }}
  with_items: "{{ app_languages }}"
  ignore_errors: yes

- name: Set default language
  command: drush @{{ app_name }}.bld language-default {{ app_languages_default|default('en') }}
  ignore_errors: yes
