---
- name: Check files source exists
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html/sites/default/files"
    follow: yes
  register: source_files

- name: Copy files from existing release to codebase dir.
  command: "cp -pur {{ deploy_webroot }}/{{ app_name }}/public_html/sites/default/files {{ codebase_dir }}/sites/default/"
  when: source_files.stat.exists
  become: yes
  become_user: root

- name: Check files dest now exists under codebase_dir
  stat:
    path: "{{ codebase_dir }}/sites/default/"
    follow: yes
  register: dest_files

- name: "Make sure the files folder exists and is owned/writable by app"
  file: 
    path: "{{ codebase_dir }}/sites/default/files"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "ug+w"
  when: dest_files.stat.exists
  become: yes
  become_user: root
