---
- name: Check files source exists
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html/sites/default/files"
    follow: yes
  register: source_files

- name: Copy files from existing release to codebase dir.
  command: "cp -pur {{ deploy_webroot }}/{{ app_name }}/public_html/sites/default/files {{ codebase_dir }}/sites/default/"
  when: source_files.stat.exists
  become: yes

- name: Check files dest now exists under codebase_dir
  stat:
    path: "{{ codebase_dir }}/sites/default/"
    follow: yes
  register: dest_files

- name: Add group write permission to the new files folder
  file: 
    path: "{{ codebase_dir }}/sites/default/files"
    mode: "g+w"
  when: dest_files.stat.exists
  become: yes 

- name: Add group ownership to the new files folder
  file: 
    path: "{{ codebase_dir }}/sites/default/files"
    group: "{{ app_group }}"
  when: dest_files.stat.exists
  become: yes
