---
- name: Make sure default files directory exists
  file:
    path: "{{ codebase_dir }}/sites/default/files"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Ensuring user/group of codebase dir
  file:
    path: "{{ codebase_dir }}"
    state: directory
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Setting new build symlink to clone the new build
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html.build"
    src: "{{ codebase_dir }}"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root
