---
- name: Make sure directory exists for the codebase dir
  file:
    path: "{{ codebase_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root
  when: not deploy_install_profile_enabled|default(False)

- name: Copy the updated codebase
  command: "cp -pr {{ cached_copy_dir }}{{ deploy_codebase_root_folder }}/. {{ codebase_dir }}"
  when: not deploy_install_profile_enabled|default(False)|bool

- name: Make sure config sync directory exists
  file:
    path: "{{ deploy_config_sync_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: app_drupal_version|default('8')|version_compare('8', '==')
  become: yes
  become_user: root

- name: Check config sync directory exists in the codebase
  stat:
    path: "{{ cached_copy_dir }}{{ deploy_codebase_config_base_dir }}/sync"
  register: deploy_codebase_check_sync_output
  when: app_drupal_version|default('8')|version_compare('8', '==')
  become: yes
  become_user: root

- name: Copy the sync configuration folder
  synchronize: 
    src: "{{ cached_copy_dir }}{{ deploy_codebase_config_base_dir }}/sync/"
    dest: "{{ deploy_config_sync_dir }}"
    delete: yes
  when: app_drupal_version|default('8')|version_compare('8', '==') and deploy_codebase_check_sync_output.stat.exists
  delegate_to: "{{ inventory_hostname }}"

- name: Make sure config env directory exists
  file:
    path: "{{ deploy_config_env_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: app_drupal_version|default('8')|version_compare('8', '==')
  become: yes
  become_user: root

- name: Check config directory exists in the codebase for the target environment
  stat:
    path: "{{ cached_copy_dir }}/{{ deploy_codebase_config_base_dir }}/{{ app_target }}"
  register: deploy_codebase_check_env_output
  when: app_drupal_version|default('8')|version_compare('8', '==')
  become: yes
  become_user: root

- name: Deploy the configuration for the target environment
  synchronize: 
    src: "{{ cached_copy_dir }}/{{ deploy_codebase_config_base_dir }}/{{ app_target }}/"
    dest: "{{ deploy_config_env_dir }}"
    delete: yes
  when: app_drupal_version|default('8')|version_compare('8', '==') and deploy_codebase_check_env_output.stat.exists
  delegate_to: "{{ inventory_hostname }}"
