---
- name: Ensure git host is a known host
  lineinfile:
    dest: /home/{{ app_env['user'] }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + git_repo_server) }}"
    regexp: "^{{ git_repo_server }}"
  when: "not accept_hostkey and git_repo_protocol is defined and (git_repo_protocol == 'ssh' or git_repo_protocol == 'git')"

- name: Make sure directory exists for the codebase dir.
  file:
    path: "{{ codebase_dir }}"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes

- name: Make sure directory exists for the cached copy dir.
  file:
    path: "{{ cached_copy_dir }}"
    state: directory
    owner: "{{ app_env['user'] }}"
  become: yes

- name: Git clone the app codebase (http/s w/o credentials)
  git:
    clone: yes
    force: yes
    version: "{{ git_version }}"
    dest: "{{ cached_copy_dir }}"
    repo: "{{ git_repo_protocol }}://{{ git_repo_server }}/{{ git_repo_path }}"
  when: "git_repo_protocol is defined and (git_repo_protocol == 'https' or git_repo_protocol == 'http') and git_repo_user is not defined"

- name: Git clone the app codebase (http/s w/credentials)
  git:
    clone: yes
    force: yes
    version: "{{ git_version }}"
    dest: "{{ cached_copy_dir }}"
    repo: '{{ git_repo_protocol }}://{{ git_repo_user }}:{{ git_repo_pass | default(lookup("password", secret + "/credentials/" + ansible_fqdn + "/git/" + git_repo_user + "/password")) }}@{{ git_repo_server }}/{{ git_repo_path }}'
  when: "git_repo_protocol is defined and (git_repo_protocol == 'https' or git_repo_protocol == 'http') and git_repo_user is defined"

- name: Git clone the app codebase (ssh)
  git:
    clone: yes
    force: yes
    version: "{{ git_version }}"
    dest: "{{ cached_copy_dir }}"
    repo: "ssh://{{ git_repo_user }}@{{ git_repo_server }}/{{ git_repo_path }}"
  when: "git_repo_protocol is defined and git_repo_protocol == 'ssh'"

- name: Git clone the app codebase (git)
  git:
    clone: yes
    force: yes
    version: "{{ git_version }}"
    dest: "{{ cached_copy_dir }}"
    repo: "git@{{ git_repo_server }}:{{ git_repo_user }}/{{ git_repo_path }}"
  when: "git_repo_protocol is defined and git_repo_protocol == 'git'"

- name: Copy the updated codebase
  command: "cp -pr {{ cached_copy_dir }}/. {{ codebase_dir }}"

- name: Make sure files directory exists
  file:
    path: "{{ codebase_dir }}/sites/default/files"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes
