---
- name: Copy templated settings.php
  template:
    src: "settings-drupal-{{ drupal_version }}.php.j2"
    dest: "{{ codebase_dir }}/sites/default/settings.php"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    mode: 0640
  sudo: yes
