---
- name: Make sure sites/default dir exists
  file:
    path: "{{ codebase_dir }}/sites/default"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes

- name: Make sure files directory exists
  file:
    path: "{{ codebase_dir }}/sites/default/files"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes

- name: Make sure settings.d directory exists
  file:
    path: "{{ codebase_dir }}/sites/default/settings.d"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes

- name: Copy templated settings.php
  template:
    src: "settings-drupal-{{ app_drupal_version.split('.', 0)|join('') }}.php.j2"
    dest: "{{ codebase_dir }}/sites/default/settings.php"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0640
  become: yes

- name: Copy templated custom settings
  template:
    src: "custom/settings.php.j2"
    dest: "{{ codebase_dir }}/sites/default/settings.d/custom.php"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0640
  become: yes
