---
- name: Make sure sites/default dir exists
  file:
    path: "{{ codebase_dir }}/sites/default"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  sudo: yes

- name: Copy templated settings.php
  template:
    src: "settings-drupal-{{ drupal_version }}.php.j2"
    dest: "{{ codebase_dir }}/sites/default/settings.php"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    mode: 0640
  become: yes

- name: Copy templated custom settings when provided
  template:
    src: "{{ deploy_custom_settings }}"
    dest: "{{ codebase_dir }}/sites/default/custom-settings.php"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    mode: 0640
  become: yes
  when: deploy_custom_settings is defined

- name: Include custom settings when provided
  lineinfile: 
    dest: "{{ codebase_dir }}/sites/default/settings.php"
    insertafter: EOF 
    line: "require_once 'custom-settings.php';"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    mode: 0640
  become: yes
  when: deploy_custom_settings is defined

- name: Make sure custom settings are absent when not provided
  lineinfile: 
    dest: "{{ codebase_dir }}/sites/default/settings.php"
    line: "require_once 'custom-settings.php';"
    state: absent
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    mode: 0640
  become: yes
  when: deploy_custom_settings is not defined
