---
- name: Look for the makefile given
  stat:
    path: "{{ codebase_dir }}/{{ deploy_drush_makefile }}"
  when: deploy_drush_make_enabled|default(False)|bool
  register: profile_makefile_chosen

- name: Run drush make makefile if makefile has been found
  command: drush make --shallow-clone {{ deploy_drush_makefile }} -y
  when: profile_makefile_chosen.stat.exists 
  args:
    chdir: "{{ codebase_dir }}"
