---
- name: Check for the makefile given
  stat:
    path: "{{ profiles_dir }}/{{ install_profile }}/{{ deploy_drush_makefile }}"
  when: deploy_drush_make_enabled|default(False)|bool
  register: profile_makefile_chosen

- name: Run drush make makefile (ignore_errors version)
  command: drush make "{{ profiles_dir }}/{{ install_profile }}/{{ deploy_drush_makefile }}" "{{ codebase_dir }}" --translations="{{ locale|join(',') }}" --shallow-clone --yes
  when: profile_makefile_chosen.stat.exists and deploy_ignore_drush_make_errors|default(False)|bool
  ignore_errors: yes

- name: Run drush make makefile
  command: drush make "{{ profiles_dir }}/{{ install_profile }}/{{ deploy_drush_makefile }}" "{{ codebase_dir }}" --translations="{{ locale|join(',') }}" --shallow-clone --yes
  when: profile_makefile_chosen.stat.exists and not deploy_ignore_drush_make_errors|default(False)|bool

- name: Look for the profile project in the build dir
  stat:
    path: "{{ codebase_dir }}{{ drupal_profiles_base_folder }}/{{ install_profile }}"
  register: profile_project_included

- name: Make sure build_dir exists (if profile not found)
  file:
    path: "{{ codebase_dir }}"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes
  when: not profile_project_included.stat.exists

- name: rsync with the profile inside the build dir
  command: rsync -a "{{ profiles_dir }}/" "{{ codebase_dir }}{{ drupal_profiles_base_folder }}"

- name: Look for libraries inside the profile project
  stat:
    path: "{{ profiles_dir }}/{{ install_profile }}/libraries"
  register: profile_libraries

- name: Make sure sites/all/libraries exists in the codebase dir
  file:
    path: "{{ codebase_dir }}/sites/all/libraries"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  when: profile_libraries.stat.exists

- name: rsync libraries between the profile and sites/all/libraries
  command: rsync -a "{{ profiles_dir }}/{{ install_profile }}/libraries/" "{{ codebase_dir }}/sites/all/libraries"
  when: profile_libraries.stat.exists
