---
- name: Look for the makefile given
  stat:
    path: "{{ profiles_dir }}/{{ install_profile }}/{{ deploy_drush_makefile }}"
  when: deploy_drush_make_enabled|default(False)|bool
  register: profile_makefile_chosen

- name: Run drush make makefile if makefile has been found
  command: drush make "{{ profiles_dir }}/{{ install_profile }}/{{ deploy_drush_makefile }}" "{{ codebase_dir }}" --shallow-clone --yes
  when: profile_makefile_chosen.stat.exists

- name: Look for the profile project in the build dir
  stat:
    path: "{{ codebase_dir }}/profiles/{{ install_profile }}"
  register: profile_project_included

- name: Make sure the profile project is present inside the build dir
  command: cp -pr "{{ profiles_dir }}/{{ install_profile }}" "{{ codebase_dir }}/profiles/"
  when: not profile_project_included.stat.exists
