---
- name: Drush site-install
  command: "drush site-install {{ install_profile }} --locale={{ locale }} --site-name={{ name }} --site-mail={{ email }} --account-pass={{ site_pass }} --yes"
  args:
    chdir: "{{ codebase_dir }}"
