---
- name: Enable purge module (first download project if not present)
  command: "drush @{{ app_name }}.bld en purge -y"
  ignore_errors: yes

- name: Enable purge submodules
  command: "drush @{{ app_name }}.bld en purge_ui purge_drush purge_queuer_coretags purge_processor_cron purge_tokens -y"
  ignore_errors: yes

- name: Enable HTTP purger module
  command: "drush @{{ app_name }}.bld en purge_purger_http -y"
  ignore_errors: yes

- name: Configure purge plugins
  command: "drush -y @{{ app_name }}.bld cset purge.plugins purgers.0.{{ item.key }} {{ item.value }}"
  with_dict: "{{ deploy_purge_plugins_purgers_config }}"

- name: Configure HTTP purger
  command: "drush -y @{{ app_name }}.bld cset purge_purger_http.settings.{{ item.key }} {{ item.value }}"
  with_dict: "{{ purge_purger_http_settings }}"

- name: Set page cache max-age
  command: "drush -y @{{ app_name }}.bld cset system.performance cache.page.max_age {{ deploy_page_cache_max_age }}"
