---
- name: Enable varnish module
  command: drush @{{ app_name }}.bld dl {{ varnish_drupal_module }}-7.x-1.x-dev -y
  ignore_errors: yes

- name: Enable varnish  module
  command: drush @{{ app_name }}.bld en {{ varnish_drupal_module }} -y
  ignore_errors: yes

- name: Configure varnish version 4
  command: drush @{{ app_name }}.bld vset varnish_version 4

- name: Configure varnish control terminal
  command: drush @{{ app_name }}.bld vset varnish_control_terminal 'localhost:{{ deploy_varnish_mgmt_port }}'

- name: Configure varnish control key
  command: drush @{{ app_name }}.bld vset varnish_control_key "{{ lookup('password', secret + '/credentials/varnish/secret chars=ascii_letters,digits,hexdigits') }}"
