---
- name: Download varnish module
  command: drush @{{ app_name }}.bld dl {{ deploy_varnish_drupal_module }} -y
  ignore_errors: yes

- name: Enable varnish module
  command: drush @{{ app_name }}.bld en {{ deploy_varnish_drupal_module }} -y
  ignore_errors: yes

- name: Configure varnish variables
  command: "drush @{{ app_name }}.bld vset {{ item.key }} {{ item.value }}"
  with_dict: "{{ deploy_varnish_variables }}"
  no_log: True
