---
- name: Enable project modules
  command: "drush @{{ app_name }}.bld en {{ lookup('file', 'deploy/enable.txt') }} -y"

- name: Enable project modules for the environment/target
  command: "drush @{{ app_name }}.bld en {{ lookup('file', 'deploy/enable-prod.txt') }} -y"
  when: target == 'prod'

- name: Disable project modules
  command: "drush @{{ app_name }}.bld dis {{ lookup('file', 'deploy/disable.txt') }} -y"

- name: Disable project modules for the environment/target
  command: "drush @{{ app_name }}.bld dis {{ lookup('file', 'deploy/disable-prod.txt') }} -y"
  when: target == 'prod'
