---
- name: Copy templated https settings
  template:
    src: "https/https-settings.php.j2"
    dest: "{{ codebase_dir }}/sites/default/settings.d/https.php"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0640
  become: yes
  become_user: root

- name: Enable securepages module
  command: drush @{{ app_name }}.bld en securepages -y

- name: Download patches to apply to securepages
  get_url:
    url: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  with_items:
    - 'https://www.drupal.org/files/drupal-https-only-961508-23-32.patch'
    - 'https://www.drupal.org/files/issues/471970_0.patch'
    
- name: Apply patches required by securepages
  patch:
    src: "/tmp/{{ item }}"
    basedir: "{{ codebase_dir }}"
    strip: 1
  with_items:
    - '471970_0.patch'
    - 'drupal-https-only-961508-23-32.patch'

- name: Configure securepages to be enabled
  command: drush @{{ app_name }}.bld vset securepages_enable '1'
