---
- name: Download varnish module
  command: drush @{{ app_name }}.bld dl {{ deploy_varnish_drupal_module }} -y
  ignore_errors: yes

- name: Enable varnish  module
  command: drush @{{ app_name }}.bld en {{ deploy_varnish_drupal_module }} -y
  ignore_errors: yes

- name: Configure varnish version 4
  command: drush @{{ app_name }}.bld vset varnish_version 4

- name: Configure varnish control terminal
  command: drush @{{ app_name }}.bld vset varnish_control_terminal 'localhost:{{ deploy_varnish_mgmt_port|default('6082') }}'

- name: Configure varnish control key
  command: drush @{{ app_name }}.bld vset varnish_control_key "{{ lookup('password', secret + '/credentials/' + app_name + '/varnish/secret chars=ascii_letters,digits,hexdigits') }}"
