---
- name: "Drop current database's tables"
  command: "drush @{{ app_name }}.bld sql-drop --yes" 

- name: Copy and decompress (unarchive) an archived SQL dump
  unarchive:
    src: "{{ app_env.db_dump_filename }}"
    dest: "/home/{{ app['user'] }}/.drush/dbdumps"
    user: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"

- name: Import the SQL dump into the current database
  shell: "$(drush @{{ app_name }}.bld sql-connect) < /home/{{ app['user'] }}/.drush/dbdumps/{{ app_env.db_dump_filename }}"
