---
- name: setup logrotate.d script for daily backups
  template:
    src: "logrotate.d/backup.j2"
    dest: "/etc/logrotate.d/{{ app_name }}-backup"
  become: yes

- name: Make sure the archive dir is present
  file:
    path: "/home/{{ app_env['user'] }}/drush-backups/archive-dump/logrotate"
    state: directory

- name: Make sure a first empty archive exists
  file:
    path: "/home/{{ app_env['user'] }}/drush-backups/archive-dump/logrotate/{{ app_name }}-ard.tar.gz"
    state: touch

- name: Force postrotate on the empty archive to kick-off the log rotation
  command: logrotate -f /etc/logrotate.d/{{ app_name }}-backup
  become: yes
