---
- name: setup logrotate.d script for daily backups
  template:
    src: "logrotate.d/backup.j2"
    dest: "/etc/logrotate.d/{{ app_name }}-backup"
  sudo: yes

- name: Make sure the archive dir is present
  file:
    path: "/home/{{ app_env['user'] }}/drush-backups/archive-dump/logrotate"
    state: directory

- name: Make sure an archive exists to kick-off the log rotation
  file:
    path: "/home/{{ app_env['user'] }}/drush-backups/archive-dump/logrotate/{{ app_name }}-ard.tar.gz"
    state: touch
