---
- name: setup logrotate.d script for the app specific log
  template:
    src: "logrotate.d/applog.j2"
    dest: "/etc/logrotate.d/{{ app['website']['host'] }}"
  when: "app['log'] is defined"
  tags: logrotate

- name: setup logrotate.d script for daily backups
  template:
    src: "logrotate.d/backup.j2"
    dest: "/etc/logrotate.d/{{ app['website']['host'] }}-backup"
  tags: logrotate

- name: run initial backup to spark the process
  command: "drush @{{  app['website']['host'] }}.cur archive-dump --tar-options=\"--exclude=.git\" --description=\"Backup of {{ app['website']['host'] }} containing codebase, files and DB.\" --destination=/home/{{  app['website']['user'] }}/drush-backups/archive-dump/logrotate/{{  app['website']['host'] }}-ard.tar.gz --overwrite"
  tags: logrotate
