---
- name: setup logrotate.d script for the app specific log
  template:
    src: "logrotate.d/applog.j2"
    dest: "/etc/logrotate.d/{{ app['website']['host'] }}"
  when: "app['log'] is defined"
  tags: logrotate

- name: setup logrotate.d script for daily backups
  template:
    src: "logrotate.d/backup.j2"
    dest: "/etc/logrotate.d/{{ app['website']['host'] }}-backup"
  tags: logrotate
