---
- include: preflight-checks.yml
  tags: [ deploy.init ]

- include: deploy-code/main.yml
  tags: [ deploy.code ]

- include: drupal-settings.yml
  vars:
    codebase_dir: "{{ deploy_webroot }}/{{ app_name }}/public_html.{{ deploy_build_id }}"
  tags: [ deploy.drupal.settings ]

- include: backup-cur-db.yml
  when: deploy_backup_cur_enabled|default(True)|bool and not app_db_create_for_build_enabled|default(False)|bool
  tags: [ deploy.provision.db, deploy.config.db ]

- include: readonly-mode.yml
  vars:
    readonly_flag: 1
  when: deploy_db_clone_enabled|default(False)|bool and not deploy_db_import_enabled|default(False)|bool and app_drupal_version|version_compare('7', '==')
  tags: [ deploy.provision.db, deploy.config.db ]

- include: site-offline.yml
  vars:
    offline_flag: 1
  when: not deploy_db_clone_enabled|default(False)|bool and not deploy_db_import_enabled|default(False)|bool
  tags: [ deploy.provision.db, deploy.config.db ]

- include: provision-db/main.yml
  tags: [ deploy.provision.db ]

- include: config-db/main.yml
  tags: [ deploy.config.db ]

- include: readonly-mode.yml
  vars:
    readonly_flag: 0
  when: deploy_db_clone_enabled|default(False)|bool and not deploy_db_import_enabled|default(False)|bool
  tags: [ deploy.provision.db, deploy.config.db ]
  
- include: site-offline.yml
  vars:
    offline_flag: 0
  when: not deploy_db_clone_enabled|default(False)|bool and not deploy_db_import_enabled|default(False)|bool
  tags: [ deploy.provision.db, deploy.config.db ]

- include: provision-files/main.yml
  tags: [ deploy.provision.files ]

- include: final-tasks/main.yml
  tags: [ deploy.final ]
