---
# TODO Add feature local git clone
# If we are local (git doesn't work in the remote)
# push branch and tag from local directory
# And don't forget to CLEAN it all UP
- name: remove current build symlink and its contents, if any
  file:
    path: "{{ webroot }}/{{ webhost }}/public_html.build"
    state: absent
    follow: yes

- include: drush-checks.yml

- include: defaults-check.yml

- include: deploy-codebase.yml
  vars:
    codebase_dir: "{{ webroot }}/{{ webhost }}_{{ build }}"

- include: logrotate.yml

- include: branch-tag.yml
  vars:
    codebase_dir: "{{ webroot }}/{{ webhost }}_{{ build }}"
  when: target == 'prod'

- include: switch-on.yml
