---
- name: Download drupal 8 projects for all OPS features
  shell: "drush @{{ app_name }}.bld dl {{ (deploy_drupal8_projects_base|d([]) + deploy_drupal8_projects|d([])) | join(' ') }} -y"
  when: app_drupal_version|version_compare('8', '==') and (deploy_drupal8_projects_base|d([]) + deploy_drupal8_projects|d([])) | length > 0

- name: Download drupal 7 projects for all OPS features
  shell: "drush @{{ app_name }}.bld dl {{ (deploy_drupal7_projects_base|d([]) + deploy_drupal7_projects|d([])) | join(' ') }} -y"
  when: app_drupal_version|version_compare('7', '==')  and (deploy_drupal7_projects_base|d([]) + deploy_drupal7_projects|d([])) | length > 0

- name: Enable Drupal 8 modules for all OPS features
  shell: "drush @{{ app_name }}.bld en {{ hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item + '_drupal8_modules_enabled']|join(' ') }} -y"
  with_items: "{{ deploy_drupal8_projects_base|d([]) + deploy_drupal8_projects|d([]) }}" 
  when: app_drupal_version|version_compare('8', '==')  and (deploy_drupal8_projects_base|d([]) + deploy_drupal8_projects|d([])) | length > 0

- name: Enable Drupal 7 modules for all OPS features
  shell: "drush @{{ app_name }}.bld en {{ hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item + '_drupal7_modules_enabled']|join(' ') }} -y"
  with_items: "{{ deploy_drupal7_projects_base|d([]) + deploy_drupal7_projects|d([]) }}"
  when: app_drupal_version|version_compare('7', '==')  and (deploy_drupal7_projects_base|d([]) + deploy_drupal7_projects|d([])) | length > 0

- name: Apply core patches for all OPS features (remote_src)
  patch: 
    src: "{{ item[1] }}"
    remote_src: yes
    strip: 1
    basedir: "{{ codebase_dir }}"
  when: item is defined
  with_nested: 
  - "{{ hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item[0] + '_core_drupal' + app_drupal_version + '_patches']|d([]) }}"
  - "{{ deploy_drupal7_projects_base|d([]) }} + {{ deploy_drupal7_projects|d([]) }} + {{ deploy_drupal8_projects_base|d([]) }} + {{ deploy_drupal8_projects|d([]) }}" 

- name: Apply project patches for all OPS features
  patch: 
    src: "{{ item[1] }}"
    remote_src: no
    strip: 1
    basedir: "{{ codebase_dir }}/{{ drush_contrib_modules_destination }}/{{ item[0] }}"
  when: item is defined
  with_nested: 
  - "{{ hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item[0] + '_patches']|d([]) }}"
  - "{{ deploy_drupal7_projects_base|d([]) }} + {{ deploy_drupal7_projects|d([]) }} + {{ deploy_drupal8_projects_base|d([]) }} + {{ deploy_drupal8_projects|d([]) }}" 

# Drupal 8 config sets
- set_fact:
    dictio__: "{{ dictio__|d({})|combine(hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item + '_config_sets' ]|d({})) }}"
  with_items: "{{ deploy_drupal8_projects_base|d([]) }} + {{ deploy_drupal8_projects|d([]) }}" 
  when: app_drupal_version|version_compare('8', '==')

- include: cset-inner.yml
  with_dict: "{{ dictio__ }}"
  # (needs an inner play called several times)
  loop_control:
    loop_var: outer_item
  when: app_drupal_version|version_compare('8', '==')

# Drupal 7 variables
- set_fact:
    variables__: "{{ dictio__|d({})|combine(hostvars[groups[app_name + '-' + app_target + '_deploy'][0]][ item + '_variables' ]|d({})) }}"
  with_items: "{{ deploy_drupal7_projects_base|d([]) }} + {{ deploy_drupal7_projects|d([]) }}" 
  when: app_drupal_version|version_compare('7', '==')

- name: Variables set
  command: "drush @{{ app_name }}.bld -y vset {{ item.key|quote }} {{ item.value|quote }}"
  with_dict: "{{ variables__ }}"
  when: app_drupal_version|version_compare('7', '==')
