---
- name: "Invalidate Views cache first (https://www.drupal.org/node/2297647)"
  command: "drush @{{ app_name }}.bld php-eval 'views_invalidate_cache();'"

- name: "Rebuild Drupal registry"
  command: "drush @{{ app_name }}.bld drush registry-rebuild"
