---
- name: Make sure logs dir exists
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes

- name: Touch and set proper permissions to drupal.log
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs/drupal.log"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0664
    state: touch
  become: yes

- name: Install rsyslog config for Drupal syslog module
  template:
    src: rsyslog/drupal.conf
    dest: /etc/rsyslog.d/drupal.conf
  notify: Restart rsyslog
  become: yes

- name: Enable syslog drupal module
  command: drush @{{ app_name }}.cur en syslog -y

- name: setup logrotate.d script for drupal log rotation
  template:
    src: "logrotate.d/drupal.j2"
    dest: "/etc/logrotate.d/drupal"
  become: yes
