---
- name: Make sure logs dir exists
  file:
    path: "{{ webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  sudo: yes

- name: Make sure drupal log file exists
  shell: touch {{ webroot }}/{{ app_name }}/logs/drupal.log creates="{{ webroot }}/{{ app_name }}/logs/drupal.log"

- name: Install rsyslog config for Drupal syslog module
  template:
    src: rsyslog/drupal.conf
    dest: /etc/rsyslog.d/drupal.conf
  sudo: yes
  notify: Restart rsyslog

- name: Enable syslog drupal module
  command: "drush @{{ app_name }}.cur en syslog -y"

- name: setup logrotate.d script for drupal log rotation
  template:
    src: "logrotate.d/drupal.j2"
    dest: "/etc/logrotate.d/drupal"
  sudo: yes
