---
- name: Take website into maintenance mode (D7)
  command: "drush @{{ app_name }}.cur vset site_offline {{ offline_flag }}"
  ignore_errors: True
  when: app_drupal_version|default('8')|version_compare('7', '==')

- name: Take website into maintenance mode
  command: "drush @{{ app_name }}.cur sset system.maintenance_mode {{ offline_flag }}"
  ignore_errors: True
  when: app_drupal_version|default('8')|version_compare('8', '==')
