---
- name: Remove .bak symlink and its contents, if it exists
  file:
    path: "{{ webroot }}/{{ app_name }}/public_html.bak"
    follow: yes
    state: absent
  become: yes

- name: Rename current symlink to .bak, if it exists
  command: "mv {{ webroot }}/{{ app_name }}/public_html {{ webroot }}/{{ app_name }}/public_html.bak"
  become: yes

- name: Set new symlink to new live codebase
  file:
    dest: "{{ webroot }}/{{ app_name }}/public_html"
    src: "{{ webroot }}/{{ app_name }}/public_html.{{ build }}"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
    state: link
  become: yes

- name: Remove current build symlink
  file:
    path: "{{ webroot }}/{{ app_name }}/public_html.build"
    state: absent
    follow: no
  become: yes

- name: Check user/public_html symlink already exists
  stat: 
    path: "/home/{{ app_env['user'] }}/public_html"
  register: stat_public_symlink

- name: Create user/public_html symlink
  file:
    src: "{{ webroot }}/{{ app_name }}/public_html"
    dest: "/home/{{ app_env['user'] }}/public_html"
    state: link
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes
  when: stat_public_symlink.stat is not defined or not stat_public_symlink.stat.exists
