---
- name: remove .bak symlink and its contents
  file:
    path: "{{ webroot }}/{{ webhost }}/public_html.bak"
    follow: yes
    state: absent

- name: rename current symlink to .bak
  file:
    path: "{{ webroot }}/{{ webhost }}/public_html.bak"
    src: "{{ webroot }}/{{ webhost }}/public_html"
    follow: yes
    state: link

- name: set new symlink to new live codebase
  file:
    path: "{{ webroot }}/{{ webhost }}/public_html"
    src: "{{ webroot }}/{{ webhost }}/public_html_{{ build }}"
    state: link

- name: remove current build symlink
  file:
    path: "{{ webroot }}/{{ webhost }}/public_html.build"
    state: absent
    follow: no

- name: Assures public_html folder exists
  file:
    path: "/home/{{ app['user'] }}/public_html"
    state: directory
    owner: "{{ app['user'] }}"
    group: "{{ app['group'] }}"
  tags: apache2

- name: Check whether public_html symlink already exists
  stat: 
    path: "/home/{{ app['user'] }}/public_html"
  register: stat_public_symlink
  tags: apache2

- name: Create public_html symlink
  file:
    src: "{{ webroot }}/{{ webhost }}/public_html"
    dest: "/home/{{ app['user'] }}/public_html"
    state: link
    owner: "{{ app['user'] }}"
    group: "{{ app['group'] }}"
  when: not stat_public_symlink.stat.exists
  tags: apache2

      