---
- name: Make sure app logs dir exists
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes

- name: Stat public_html for cur vhost
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html"
  register: public_html_symlink

- name: Create temp public_html symlink for cur vhost if missing
  file:
    dest: "{{ deploy_webroot }}/{{ app_name }}/public_html"
    src: "/tmp"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: not public_html_symlink.stat.exists
  become: yes

- name: Stat public_html for bak vhost
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html.bak"
  register: public_html_symlink_bak

- name: Create temp public_html symlink for bak vhost if missing
  file:
    dest: "{{ deploy_webroot }}/{{ app_name }}/public_html.bak"
    src: "/tmp"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: not public_html_symlink_bak.stat.exists
  become: yes

- name: Remove current build symlink and its contents, if any
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/public_html.build"
    state: absent
    follow: yes
  become: yes
