---
- name: Prepare to sync, ensure remote host is a known host
  lineinfile:
    dest: /home/{{ app_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + deploy_upstream_remote_host) }}"
    regexp: "^{{ deploy_upstream_remote_host }}"

- name: Sync the additional/latest files from source.
  command: "drush -y rsync @{{ app_name }}.src:%files @{{ app_name }}.bld:%files"
  when: deploy_files_sync_enabled|default(False)|bool
  ignore_errors: yes
