---
- name: "Drop current database's tables."
  command: "drush @{{ app_name }}.cur sql-drop --yes" 
  when: "app_env is defined and app_env.mode == 'same'"
  register: dropped

- name: "Sync source database with current database."
  command: "drush -y sql-sync @{{ app_name }}.src @{{ app_name }}.cur" 
  when: dropped|success
  register: synced

- name: "Rebuild Drupal registry."
  command: "drush @{{ app_name }}.cur registry-rebuild" 
  when: synced|success
