---
- name: Copy and decompress codebase tarball
  unarchive:
    src: "codebase-tarballs/{{ codebase_tarball_filename }}"
    dest: "{{ codebase_dir }}"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  become: yes
