---
- name: Make sure codebase dir exists
  file:
    path: "{{ codebase_dir }}"
    state: directory
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  sudo: yes

- name: Copy and decompress codebase tarball
  unarchive:
    src: "codebase-tarballs/{{ codebase_tarball_filename }}"
    dest: "{{ codebase_dir }}"
    owner: "{{ app_env['user'] }}"
    group: "{{ app_env['group'] }}"
  sudo: yes
