---
- name: Copy and decompress files tarball
  unarchive:
    src: "files-tarballs/{{ deploy_files_tarball_filename }}"
    dest: "{{ codebase_dir }}/sites/default/"
    mode: "g+w"
    group: "{{ app_group }}"
  become: yes
  become_user: root
