---
- name: Enable app modules
  command: "drush @{{ app_name }}.bld en {{ deploy_modules_present_app|join(' ') }} -y"
  when: deploy_modules_present_app|length > 0
  ignore_errors: yes

- name: Enabled modules in the target environment
  command: "drush @{{ app_name }}.bld en {{ deploy_modules_present_env|join(' ') }} -y"
  when: deploy_modules_present_env|length > 0
  ignore_errors: yes

- name: Disable app modules (D7)
  command: "drush @{{ app_name }}.bld dis {{ deploy_modules_absent_app|join(' ') }} -y"
  when: app_drupal_version|version_compare('7', '==') and deploy_modules_absent_app|length > 0
  ignore_errors: yes

- name: Uninstall app modules (D8)
  command: "drush @{{ app_name }}.bld pm-uninstall {{ deploy_modules_absent_app|join(' ') }} -y"
  when: app_drupal_version|version_compare('8', '==') and deploy_modules_absent_app|length > 0
  ignore_errors: yes

- name: Disabled modules in the target environment (D7)
  command: "drush @{{ app_name }}.bld dis {{ deploy_modules_absent_env|join(' ') }} -y"
  when: app_drupal_version|version_compare('7', '==') and deploy_modules_absent_env|length > 0
  ignore_errors: yes

- name: Uninstalled modules in the target environment (D8)
  command: "drush @{{ app_name }}.bld pm-uninstall {{ deploy_modules_absent_env|join(' ') }} -y"
  when: app_drupal_version|version_compare('8', '==') and deploy_modules_absent_env|length > 0
  ignore_errors: yes
