---
#
# Drupal config DB tasks
#
- include: registry-rebuild.yml
  vars:
    codebase_dir: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.{{ deploy_build_id }}"
  when: app_drupal_version|version_compare('7', '==')

- include: ops-features.yml
  vars:
    codebase_dir: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.{{ deploy_build_id }}"

- include: enable-disable-modules.yml

- include: adjust-db.yml
  when: deploy_rectify_db_enabled|default(True)|bool and app_drupal_version|version_compare('7', '==')

- include: import-config.yml
  when: deploy_rectify_db_enabled|default(True)|bool and app_drupal_version|version_compare('8', '==')

- include: reset-admin-pass.yml
  when: deploy_reset_admin_pass|default(False)|bool

- include: config-languages-d7.yml
  vars:
    codebase_dir: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.{{ deploy_build_id }}"
  when: deploy_site_install_enabled|default(False)|bool and app_i18n_enabled|default(False)|bool and app_drupal_version|default('8')|version_compare('7', '==')
