---
- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  become: yes

- name: Restart php-fpm
  service:
    name: "{{ deploy_php_service_name }}"
    state: restarted
  become: yes
