---
- name: Ensure zip/unzip are installed
  package:
    name: zip
    state: present
    use: apt
  become: yes
  become_user: root

- name: Make sure directory exists for the codebase dir
  file:
    path: "{{ codebase_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Copy and decompress codebase tarball
  unarchive:
    src: "codebase-tarballs/{{ deploy_codebase_tarball_filename }}"
    dest: "{{ codebase_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root
