---
- name: Check for composer.json
  stat:
    path: "{{ composer_base_dir }}/composer.json"
  register: deploy_composer_json

- name: Fail if composer.json not found
  fail: msg="composer.json not found"
  when: not deploy_composer_json.stat.exists

- name: Run composer install
  composer:
    command: update
    working_dir: "{{ composer_base_dir }}"
