---
- name: Make sure default files directory exists
  file:
    path: "{{ codebase_dir }}/sites/default/files"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Ensuring user/group of codebase dir
  file:
    path: "{{ codebase_dir }}"
    state: directory
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Setting new build symlink to clone the new build
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.build"
    src: "{{ codebase_dir }}"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  become: yes
  become_user: root

- name: Check whether CHANGELOG.txt exists
  stat:
    path: "{{ codebase_dir }}/CHANGELOG.txt"
  register: changelog_output
  become: yes
  become_user: root

- name: Ensure CHANGELOG.txt isn't publicly accesible
  file:
    path: "{{ codebase_dir }}/CHANGELOG.txt"
    mode: "a-r"
  when: changelog_output.stat.exists
  become: yes
  become_user: root
