---
- name: Make sure app dir exists and is writable
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775
  become: yes
  become_user: root

- name: Make sure app logs dir exists and is writable
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/logs"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775
  become: yes
  become_user: root

- name: Stat public_html for cur vhost
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}"
  register: public_html_symlink

- name: Create temp public_html symlink for cur vhost if missing
  file:
    dest: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}"
    src: "/tmp"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: not public_html_symlink.stat.exists
  become: yes
  become_user: root

- name: Stat public_html for bak vhost
  stat:
    path: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.bak"
  register: public_html_symlink_bak

- name: Create temp public_html symlink for bak vhost if missing
  file:
    dest: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.bak"
    src: "/tmp"
    state: link
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  when: not public_html_symlink_bak.stat.exists
  become: yes
  become_user: root

- name: Remove current build symlink and its contents, if any
  file:
    path: "{{ deploy_webroot }}/{{ app_name }}/{{ deploy_public_html_folder }}.build"
    state: absent
    follow: yes
  become: yes
  become_user: root
